import React, { createContext, useContext, useState, ReactNode } from 'react';

type LanguageCode = string;

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  n: (num: number | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const numberMaps: Record<string, string[]> = {
  hi: ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'],
  bn: ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'],
  te: ['౦', '౧', '౨', '౩', '౪', '౫', '౬', '౭', '౮', '౯'],
  mr: ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'],
  gu: ['૦', '૧', '૨', '૩', '૪', '૫', '૬', '૭', '૮', '૯'],
  kn: ['೦', '೧', '೨', '೩', '೪', '೫', '೬', '೭', '೮', '೯'],
  ml: ['൦', '൧', '൨', '൩', '൪', '൫', '൬', '൭', '൮', '൯'],
  pa: ['੦', '੧', '੨', '੩', '੪', '੫', '੬', '੭', '੮', '੯'],
};

// Core UI Translations
const translations: Record<string, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.new': 'New',
    'nav.analysis': 'Analysis',
    'nav.tracker': 'Tracker',
    'nav.complaints': 'Complaints',
    'nav.profile': 'Profile',
    'hero.welcome': 'Welcome back,',
    'hero.desc': 'Your citizen portal for a better community. Report issues, track progress, and stay informed.',
    'hero.new_complaint': 'New Complaint',
    'stats.pending': 'Pending Review',
    'stats.active': 'Active Processing',
    'stats.resolved': 'Resolved Issues',
    'section.recent': 'Recent Activity',
    'section.council': 'Local Council',
    'council.desc': 'Lend your voice to community planning meetings every Tuesday.',
    'council.learn': 'Learn More',
    'btn.continue': 'Continue',
    'btn.register': 'Register as Member',
    'btn.processing': 'Processing...',
    'success.registered': 'Successfully Registered!',
    'welcome.council': 'Welcome to the Council, Citizen',
    'modal.resources': 'Community Resources',
    'emergency.directory': 'Emergency Directory',
    'emergency.helpline': 'Municipal Helpline',
    'emergency.police': 'Local Police Station',
    'emergency.fire': 'Fire & Rescue Department',
    'emergency.available': 'Available 24/7',
    'council.upcoming': 'Upcoming Sessions',
    'council.register': 'Register as Member',
    'links.quick': 'Quick Links',
    'links.gazette': 'Official Gazette',
    'links.works': 'Public Works Map',
    'notif.title': 'Notifications',
    'notif.empty': 'No notifications yet',
    'notif.emptyDesc': "We'll notify you when your reports are updated.",
    'notif.clearAll': 'Clear All',
    'lang.welcome': 'Welcome, {name}',
    'lang.select': 'Please select your preferred language to continue',
    'settings.title': 'Portal Settings',
    'settings.lang': 'Interface Language',
    'settings.theme': 'Visual Theme',
    'settings.logout': 'Sign Out',
    'stats.alert': 'City Alert',
    'active_reports.title': 'My Active Reports',
    'active_reports.view_all': 'View All',
    'active_reports.empty': "You haven't submitted any reports yet.",
    'active_reports.empty_cta': 'Submit your first complaint',
    'activity.recent': 'Recent Activity',
    'activity.empty': 'No recent activity records. Submit a report to begin tracking.',
    'alert.text': 'Water main maintenance scheduled for sector 4G tomorrow at 08:00 AM.',
    'alert.map': 'View Impact Map',
    'tracker.case_no': 'Case #',
    'tracker.title': 'Pothole Damage & Street Lighting Failure',
    'tracker.active_status': 'Active Resolution',
    'tracker.desc': 'Large pothole formed at the intersection of Maple and 4th Street following heavy rain. The adjacent street light (ID: SL-402) is also flickering, creating a safety hazard for night-time drivers and pedestrians. Reported on October 12, 2023.',
    'tracker.category': 'CATEGORY',
    'tracker.infra': 'Infrastructure',
    'tracker.location': 'LOCATION',
    'tracker.loc_val': 'District 4 - Westview',
    'tracker.priority': 'PRIORITY',
    'tracker.high_urgency': 'High Urgency',
    'tracker.timeline': 'Resolution Timeline',
    'tracker.est_completion': 'EST. COMPLETION',
    'tracker.reported': 'Reported',
    'tracker.assessed': 'Assessed',
    'tracker.in_progress': 'In Progress',
    'tracker.resolved': 'Resolved',
    'tracker.overall_status': 'Overall Status',
    'tracker.processed': 'Processed',
    'tracker.assignees': 'Assignees',
    'month.oct': 'OCT',
    'emergency.central.name': 'Emergency Central',
    'emergency.police.name': 'Local Police Station',
    'emergency.police.address': '42 Citizen Road, Sector 5, Civic District',
    'emergency.fire.name': 'Fire & Rescue Department',
    'emergency.fire.address': '88 Rescue Lane, West Zone',
    'emergency.helpline.name': 'Municipal Helpline',
    'emergency.helpline.address': 'Civic Hall, Main Square',
    'meeting.town_hall': 'Quarterly Town Hall',
    'meeting.waste': 'Waste Management Special Session',
    'meeting.location.auditorium': 'Municipal Auditorium',
    'meeting.location.center': 'Community Center Hall A',
    'month.may': 'May',
    'analysis.title': 'Analysis Report',
    'analysis.complaint_id': 'Complaint ID',
    'analysis.ai_processed': 'AI PROCESSED',
    'analysis.original': 'Original Submission',
    'analysis.category': 'Detected Category',
    'analysis.urgency': 'Urgency Level',
    'analysis.priority': 'Priority',
    'analysis.immediate': 'Immediate resolution required.',
    'analysis.short_term': 'Resolution expected within short timeframe.',
    'analysis.suggested': 'Suggested Next Actions',
    'analysis.strategic': '3 STRATEGIC RECOMMENDATIONS',
    'analysis.discard': 'Discard Analysis',
    'analysis.execute': 'Execute All Actions',
    'complaint.title': 'Submit New Complaint',
    'complaint.desc': 'Detail the civic issue you\'ve encountered. Our AI-driven system will analyze your input to categorize and prioritize it for government action.',
    'complaint.label': 'COMPLAINT DESCRIPTION',
    'complaint.placeholder': 'Please describe the issue in detail. Include specific locations, timestamps, and the impact on the community. For example: \'Large pothole at the intersection of 5th and Main, causing traffic delays and vehicle damage...\'',
    'complaint.analysis_loading': 'AI is analyzing your complaint...',
    'complaint.analysis_desc': 'We\'re categorizing and assessing the risk of your report.',
    'complaint.listening': 'Listening...',
    'complaint.info': 'Clear, descriptive text helps speed up the resolution process. Press Enter to analyze.',
    'complaint.add_photo': 'ADD PHOTO',
    'complaint.attach_file': 'ATTACH FILE',
    'complaint.tips': 'Pro Tips',
    'complaint.tip1': 'Mention nearby landmarks or street numbers.',
    'complaint.tip2': 'Specify how long the issue has been persisting.',
    'complaint.tip3': 'Attach multiple angles for physical infrastructure issues.',
    'complaint.pin_location': 'PIN LOCATION',
    'complaint.search_placeholder': 'Search for an address or landmark...',
    'complaint.locating': 'Locating you... Tap map to pin the exact problem location.',
    'complaint.pinned': 'Pinned: ',
    'complaint.auto_save': 'Draft Auto-Saved',
    'complaint.save_draft': 'SAVE DRAFT',
    'complaint.analyze_btn': 'ANALYZE COMPLAINT',
    'profile.title': 'Your Profile',
    'profile.upload': 'Upload Photo',
    'profile.take_photo': 'Take New Photo',
    'profile.full_name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save Changes',
    'profile.identity_title': 'Identity Information',
    'profile.identity_desc': 'Your profile details and official photo are used to verify your identity when reviewing infrastructure reports. Ensure your name matches your government-issued ID for faster verification.',
    'profile.sign_out': 'Sign Out',
    'profile.sign_out_desc': 'Disconnect your session from this device',
    'profile.logout': 'Logout',
    'profile.take_photo_modal': 'Take Profile Photo',
    'profile.capture': 'Capture',
    'tracker.rating': 'Rate Resolution',
    'tracker.days_to_solve': 'Days to Resolve',
    'tracker.estimated': 'Estimated',
    'tracker.days': 'Days',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.new': 'नया',
    'nav.analysis': 'विश्लेषण',
    'nav.tracker': 'ट्रैकर',
    'nav.complaints': 'शिकायतें',
    'nav.profile': 'प्रोफ़ाइल',
    'hero.welcome': 'स्वागत है,',
    'hero.desc': 'बेहतर समुदाय के लिए आपका नागरिक पोर्टल। मुद्दों की रिपोर्ट करें, प्रगति को ट्रैक करें और सूचित रहें।',
    'hero.new_complaint': 'नई शिकायत',
    'stats.pending': 'लंबित समीक्षा',
    'stats.active': 'सक्रिय प्रसंस्करण',
    'stats.resolved': 'सुलझाए गए मुद्दे',
    'section.recent': 'हाल की गतिविधि',
    'section.council': 'स्थानीय परिषद',
    'council.desc': 'हर मंगलवार को सामुदायिक योजना बैठकों में अपनी आवाज उठाएं।',
    'council.learn': 'और जानें',
    'btn.continue': 'जारी रखें',
    'btn.register': 'सदस्य के रूप में पंजीकरण करें',
    'btn.processing': 'प्रसंस्करण...',
    'success.registered': 'सफलतापूर्वक पंजीकृत!',
    'welcome.council': 'परिषद में आपका स्वागत है, नागरिक',
    'modal.resources': 'सामुदायिक संसाधन',
    'emergency.directory': 'आपातकालीन निर्देशिका',
    'emergency.helpline': 'नगरपालिका हेल्पलाइन',
    'emergency.police': 'स्थानीय पुलिस स्टेशन',
    'emergency.fire': 'अग्नि और बचाव विभाग',
    'emergency.available': '24/7 उपलब्ध',
    'council.upcoming': 'आगामी सत्र',
    'council.register': 'सदस्य के रूप में पंजीकरण करें',
    'links.quick': 'त्वरित लिंक',
    'links.gazette': 'आधिकारिक राजपत्र',
    'links.works': 'लोक निर्माण मानचित्र',
    'notif.title': 'सूचनाएं',
    'notif.empty': 'अभी तक कोई सूचना नहीं है',
    'notif.emptyDesc': 'आपके रिपोर्ट अपडेट होने पर हम आपको सूचित करेंगे।',
    'notif.clearAll': 'सभी साफ करें',
    'lang.welcome': 'स्वागत है, {name}',
    'lang.select': 'जारी रखने के लिए कृपया अपनी पसंदीदा भाषा चुनें',
    'settings.title': 'पोर्टल सेटिंग्स',
    'settings.lang': 'इंटरफ़ेस भाषा',
    'settings.theme': 'दृश्य थीम',
    'settings.logout': 'साइन आउट',
    'stats.alert': 'शहर अलर्ट',
    'active_reports.title': 'मेरी सक्रिय रिपोर्ट',
    'active_reports.view_all': 'सभी देखें',
    'active_reports.empty': 'आपने अभी तक कोई रिपोर्ट सबमिट नहीं की है।',
    'active_reports.empty_cta': 'अपनी पहली शिकायत सबमिट करें',
    'activity.recent': 'हाल की गतिविधि',
    'activity.empty': 'कोई हालिया गतिविधि रिकॉर्ड नहीं। ट्रैकिंग शुरू करने के लिए एक रिपोर्ट सबमिट करें।',
    'alert.text': 'सेक्टर 4G के लिए कल सुबह 10:00 बजे पानी के रखरखाव की योजना बनाई गई है।',
    'alert.map': 'प्रभाव मानचित्र देखें',
    'tracker.case_no': 'मामला #',
    'tracker.title': 'पोटहोल क्षति और स्ट्रीट लाइटिंग विफलता',
    'tracker.active_status': 'सक्रिय समाधान',
    'tracker.desc': 'भारी बारिश के बाद मेपल और 4वें स्ट्रीट के चौराहे पर बड़ा पोटहोल बन गया। बगल की स्ट्रीट लाइट (आईडी: SL-402) भी टिमटिवा रही है, जो रात के ड्राइवरों और पैदल चलने वालों के लिए सुरक्षा खतरा पैदा कर रही है। 12 अक्टूबर, 2023 को रिपोर्ट किया गया।',
    'tracker.category': 'श्रेणी',
    'tracker.infra': 'बुनियादी ढांचा',
    'tracker.location': 'स्थान',
    'tracker.loc_val': 'जिला 4 - वेस्टव्यू',
    'tracker.priority': 'प्राथमिकता',
    'tracker.high_urgency': 'उच्च तात्कालिकता',
    'tracker.timeline': 'समाधान समयरेखा',
    'tracker.est_completion': 'अनुमानित पूर्णता',
    'tracker.reported': 'रिपोर्ट किया गया',
    'tracker.assessed': 'आकलन किया गया',
    'tracker.in_progress': 'प्रगति पर है',
    'tracker.resolved': 'सुलझाया गया',
    'tracker.overall_status': 'कुल स्थिति',
    'tracker.processed': 'संसाधित',
    'tracker.assignees': 'सौंपा गया',
    'month.oct': 'अक्टूबर',
    'emergency.central.name': 'आपातकालीन केंद्रीय',
    'emergency.police.name': 'स्थानीय पुलिस स्टेशन',
    'emergency.police.address': '42 सिटीजन रोड, सेक्टर 5, सिविक डिस्ट्रिक्ट',
    'emergency.fire.name': 'अग्नि और बचाव विभाग',
    'emergency.fire.address': '88 रेस्क्यू लेन, वेस्ट ज़ोन',
    'emergency.helpline.name': 'नगरपालिका हेल्पलाइन',
    'emergency.helpline.address': 'सिविक हॉल, मेन स्क्वायर',
    'meeting.town_hall': 'त्रैमासिक टाउन हॉल',
    'meeting.waste': 'अपशिष्ट प्रबंधन विशेष सत्र',
    'meeting.location.auditorium': 'नगरपालिका सभागार',
    'meeting.location.center': 'सामुदायिक केंद्र हॉल ए',
    'month.may': 'मई',
    'analysis.title': 'विश्लेषण रिपोर्ट',
    'analysis.complaint_id': 'शिकायत आईडी',
    'analysis.ai_processed': 'एआई संसाधित',
    'analysis.original': 'मूल सबमिशन',
    'analysis.category': 'पहचानी गई श्रेणी',
    'analysis.urgency': 'तात्कालिकता स्तर',
    'analysis.priority': 'प्राथमिकता',
    'analysis.immediate': 'तत्काल समाधान आवश्यक।',
    'analysis.short_term': 'कम समय सीमा के भीतर समाधान की उम्मीद है।',
    'analysis.suggested': 'सुझाए गए अगले कदम',
    'analysis.strategic': '3 रणनीतिक सिफारिशें',
    'analysis.discard': 'विश्लेषण छोड़ें',
    'analysis.execute': 'सभी कार्रवाइयां निष्पादित करें',
    'complaint.title': 'नई शिकायत सबमिट करें',
    'complaint.desc': 'आपके द्वारा अनुभव की गई नागरिक समस्या का विवरण दें। हमारा एआई-संचालित सिस्टम सरकारी कार्रवाई के लिए इसे वर्गीकृत और प्राथमिकता देने के लिए आपके इनपुट का विश्लेषण करेगा।',
    'complaint.label': 'शिकायत का विवरण',
    'complaint.placeholder': 'कृपया समस्या का विस्तार से वर्णन करें। विशिष्ट स्थान, समय और समुदाय पर प्रभाव शामिल करें। उदाहरण के लिए: \'5वें और मुख्य के चौराहे पर बड़ा पोटहोल, जिससे यातायात में देरी और वाहन क्षति हो रही है...\'',
    'complaint.analysis_loading': 'AI आपकी शिकायत का विश्लेषण कर रहा है...',
    'complaint.analysis_desc': 'हम आपकी रिपोर्ट के जोखिम को वर्गीकृत और मूल्यांकन कर रहे हैं।',
    'complaint.listening': 'सुन रहा हूँ...',
    'complaint.info': 'स्पष्ट, वर्णनात्मक पाठ समाधान प्रक्रिया को तेज करने में मदद करता है। विश्लेषण के लिए Enter दबाएं।',
    'complaint.add_photo': 'फोटो जोड़ें',
    'complaint.attach_file': 'फ़ाइल संलग्न करें',
    'complaint.tips': 'प्रो टिप्स',
    'complaint.tip1': 'आस-पास के लैंडमार्क या सड़क नंबरों का उल्लेख करें।',
    'complaint.tip2': 'बताएं कि समस्या कितने समय से बनी हुई है।',
    'complaint.tip3': 'भौतिक बुनियादी ढांचे के मुद्दों के लिए कई कोण संलग्न करें।',
    'complaint.pin_location': 'पिन स्थान',
    'complaint.search_placeholder': 'पता या लैंडमार्क खोजें...',
    'complaint.locating': 'आपको खोज रहे हैं... समस्या के सटीक स्थान को पिन करने के लिए मानचित्र पर टैप करें।',
    'complaint.pinned': 'पिन किया गया: ',
    'complaint.auto_save': 'ड्राफ्ट स्वतः सहेजा गया',
    'complaint.save_draft': 'ड्राफ्ट सहेजें',
    'complaint.analyze_btn': 'शिकायत का विश्लेषण करें',
    'profile.title': 'आपकी प्रोफ़ाइल',
    'profile.upload': 'फोटो अपलोड करें',
    'profile.take_photo': 'नई फोटो लें',
    'profile.full_name': 'पूरा नाम',
    'profile.email': 'ईमेल पता',
    'profile.cancel': 'रद्द करें',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.identity_title': 'पहचान की जानकारी',
    'profile.identity_desc': 'बुनियादी ढांचे की रिपोर्टों की समीक्षा करते समय आपकी पहचान सत्यापित करने के लिए आपके प्रोफ़ाइल विवरण और आधिकारिक फोटो का उपयोग किया जाता है। सुनिश्चित करें कि आपका नाम तेजी से सत्यापन के लिए आपकी सरकारी आईडी से मेल खाता है।',
    'profile.sign_out': 'साइन आउट',
    'profile.sign_out_desc': 'इस डिवाइस से अपना सत्र डिस्कनेक्ट करें',
    'profile.logout': 'लॉगआउट',
    'profile.take_photo_modal': 'प्रोफ़ाइल फोटो लें',
    'profile.capture': 'कैप्चर',
    'tracker.rating': 'समाधान रेट करें',
    'tracker.days_to_solve': 'समाधान के लिए दिन',
    'tracker.estimated': 'अनुमानित',
    'tracker.days': 'दिन',
  },
  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.new': 'নতুন',
    'nav.analysis': 'বিশ্লেষণ',
    'nav.tracker': 'ট্র্যাকার',
    'nav.complaints': 'অভিযোগ',
    'nav.profile': 'প্রোফাইল',
    'hero.welcome': 'স্বাগতম,',
    'hero.desc': 'উন্নত সম্প্রদায়ের জন্য আপনার নাগরিক পোর্টাল। সমস্যা রিপোর্ট করুন, অগ্রগতি ট্র্যাক করুন।',
    'hero.new_complaint': 'নতুন অভিযোগ',
    'stats.pending': 'বিবেচনাধীন',
    'stats.active': 'প্রক্রিয়াধীন',
    'stats.resolved': 'সমাধান হয়েছে',
    'section.recent': 'সাম্প্রতিক কার্যকলাপ',
    'section.council': 'স্থানীয় কাউন্সিল',
    'council.desc': 'প্রতি মঙ্গলবার পরিকল্পনা সভায় আপনার মতামত জানান।',
    'council.learn': 'আরও জানুন',
    'btn.continue': 'চালিয়ে যান',
    'btn.register': 'সদস্য হিসেবে নিবন্ধন করুন',
    'btn.processing': 'প্রক্রিয়াকরণ হচ্ছে...',
    'success.registered': 'সফলভাবে নিবন্ধিত!',
    'welcome.council': 'কাউন্সিলে স্বাগতম, নাগরিক',
    'modal.resources': 'সম্প্রদায় সম্পদ',
    'emergency.directory': 'জরুরী ডিরেক্টরি',
    'emergency.helpline': 'পৌর হেল্পলাইন',
    'emergency.police': 'স্থানীয় পুলিশ স্টেশন',
    'emergency.fire': 'ফায়ার সার্ভিস',
    'emergency.available': '২৪/৭ উপলব্ধ',
    'council.upcoming': 'আসন্ন অধিবেশন',
    'council.register': 'নিবন্ধন করুন',
    'links.quick': 'দ্রুত লিঙ্ক',
    'links.gazette': 'অফিসিয়াল গেজেট',
    'links.works': 'পাবলিক ওয়ার্কস ম্যাপ',
    'notif.title': 'বিজ্ঞপ্তি',
    'notif.empty': 'কোন বিজ্ঞপ্তি নেই',
    'notif.emptyDesc': 'রিপোর্ট আপডেট হলে আমরা জানাব।',
    'notif.clearAll': 'সব মুছুন',
    'lang.welcome': 'স্বাগতম, {name}',
    'lang.select': 'পছন্দসই ভাষা নির্বাচন করুন',
    'settings.title': 'পোর্টাল সেটিংস',
    'settings.lang': 'ভাষা',
    'settings.theme': 'থিম',
    'settings.logout': 'লগ আউট',
  },
  te: {
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.new': 'కొత్తది',
    'nav.analysis': 'విశ్లేషణ',
    'nav.tracker': 'ట్రాకర్',
    'nav.complaints': 'ఫిర్యాదులు',
    'nav.profile': 'ప్రొఫైల్',
    'hero.welcome': 'స్వాగతం,',
    'hero.desc': 'మెరుగైన సమాజం కోసం మీ పౌర పోర్టల్. సమస్యలను నివేదించండి, పురోగతిని ట్రాక్ చేయండి.',
    'hero.new_complaint': 'కొత్త ఫిర్యాదు',
    'stats.pending': 'పెండింగ్ సమీక్ష',
    'stats.active': 'క్రియాశీల ప్రాసెసింగ్',
    'stats.resolved': 'పరిష్కరించబడినవి',
    'section.recent': 'ఇటీవలి కార్యాచరణ',
    'section.council': 'స్థానిక మండలి',
    'council.desc': 'ప్రతి మంగళవారం జరిగే సామాజిక ప్రణాళిక సమావేశాలలో మీ గళాన్ని వినిపించండి.',
    'council.learn': 'మరింత తెలుసుకోండి',
    'btn.continue': 'కొనసాగించు',
    'btn.register': 'సభ్యునిగా నమోదు చేసుకోండి',
    'btn.processing': 'ప్రాసెస్ అవుతోంది...',
    'success.registered': 'విజయవంతంగా నమోదు చేయబడింది!',
    'welcome.council': 'కౌన్సిల్‌కు స్వాగతం, పౌరుడా',
    'modal.resources': 'సామాజిక వనరులు',
    'emergency.directory': 'అత్యవసర డైరెక్టరీ',
    'emergency.helpline': 'మునిసిపల్ హెల్ప్‌లైన్',
    'emergency.police': 'స్థానిక పోలీస్ స్టేషన్',
    'emergency.fire': 'ఫైర్ & రెస్క్యూ విభాగం',
    'emergency.available': '24/7 అందుబాటులో ఉంది',
    'council.upcoming': 'రాబోయే సెషన్లు',
    'council.register': 'సభ్యునిగా నమోదు చేసుకోండి',
    'links.quick': 'త్వరిత లింకులు',
    'links.gazette': 'అధికారిక గెజెట్',
    'links.works': 'పబ్లిక్ వర్క్స్ మ్యాప్',
    'notif.title': 'నోటిఫికేషన్లు',
    'notif.empty': 'ఇంకా నోటిఫికేషన్లు లేవు',
    'notif.emptyDesc': 'మీ నివేదికలు నవీకరించబడినప్పుడు మేము మీకు తెలియజేస్తాము.',
    'notif.clearAll': 'అన్నింటినీ క్లియర్ చేయండి',
    'lang.welcome': 'స్వాగతం, {name}',
    'lang.select': 'కొనసాగడానికి దయచేసి మీకు ఇష్టమైన భాషను ఎంచుకోండి',
    'settings.title': 'సెట్టింగ్స్',
    'settings.lang': 'భాష',
    'settings.theme': 'థీమ్',
    'settings.logout': 'లాగ్ అవుట్',
  },
  ta: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.new': 'புதியது',
    'nav.analysis': 'பகுப்பாய்வு',
    'nav.tracker': 'டிராக்கர்',
    'nav.complaints': 'புகார்கள்',
    'nav.profile': 'சுயவிவரம்',
    'hero.welcome': 'வரவேற்கிறோம்,',
    'hero.desc': 'சிறந்த சமூகத்திற்கான உங்கள் குடிமக்கள் போர்டல். சிக்கல்களைப் புகாரளிக்கவும், முன்னேற்றத்தைக் கண்காணிக்கவும்.',
    'hero.new_complaint': 'புதிய புகார்',
    'stats.pending': 'நிலுவையில் உள்ள மதிப்பாய்வு',
    'stats.active': 'செயலில் உள்ள செயலாக்கம்',
    'stats.resolved': 'தீர்க்கப்பட்ட சிக்கல்கள்',
    'section.recent': 'சமீபத்திய செயல்பாடு',
    'section.council': 'உள்ளூர் கவுன்சில்',
    'council.desc': 'ஒவ்வொரு செவ்வாய்க்கிழமையும் திட்டமிடல் கூட்டங்களில் உங்கள் குரலை எழுப்புங்கள்.',
    'council.learn': 'மேலும் அறிய',
    'btn.continue': 'தொடரவும்',
    'btn.register': 'உறுப்பினராக பதிவு செய்யவும்',
    'btn.processing': 'செயலாக்கம்...',
    'success.registered': 'வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    'welcome.council': 'கவுன்சிலுக்கு வரவேற்கிறோம், குடிமகனே',
    'modal.resources': 'சமூக வளங்கள்',
    'emergency.directory': 'அவசர கால அடைவு',
    'emergency.helpline': 'நகராட்சி உதவி எண்',
    'emergency.police': 'உள்ளூர் காவல் நிலையம்',
    'emergency.fire': 'தீயணைப்பு மற்றும் மீட்புத் துறை',
    'emergency.available': '24/7 கிடைக்கிறது',
    'council.upcoming': 'வரவிருக்கும் அமர்வுகள்',
    'council.register': 'உறுப்பினராக பதிவு செய்யவும்',
    'links.quick': 'விரைவான இணைப்புகள்',
    'links.gazette': 'அதிகாரப்பூர்வ வர்த்தமானி',
    'links.works': 'பொதுப்பணி வரைபடம்',
    'notif.title': 'அறிவிப்புகள்',
    'notif.empty': 'இன்னும் அறிவிப்புகள் இல்லை',
    'notif.emptyDesc': 'உங்கள் புகார்கள் புதுப்பிக்கப்படும்போது நாங்கள் உங்களுக்கு அறிவிப்போம்.',
    'notif.clearAll': 'அனைத்தையும் அழிக்கவும்',
    'lang.welcome': 'வரவேற்கிறோம், {name}',
    'lang.select': 'தொடர உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    'settings.title': 'அமைப்புகள்',
    'settings.lang': 'மொழி',
    'settings.theme': 'தீம்',
    'settings.logout': 'வெளியேறு',
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.new': 'नवीन',
    'nav.analysis': 'विश्लेषण',
    'nav.tracker': 'ट्रॅकर',
    'nav.complaints': 'तक्रारी',
    'nav.profile': 'प्रोफाइल',
    'hero.welcome': 'स्वागत आहे,',
    'hero.desc': 'तुमच्या समुदायासाठी तुमचे नागरिक पोर्टल. समस्यांची तक्रાર करा आणि प्रगती पहा.',
    'hero.new_complaint': 'नवीन तक्रार',
    'stats.pending': 'प्रलंबित पुनरावलोकन',
    'stats.active': 'सक्रिय प्रक्रिया',
    'stats.resolved': 'सुटलेल्या समस्या',
    'section.recent': 'अलीकडील क्रियाकलाप',
    'section.council': 'स्थानिक परिषद',
    'council.desc': 'प्रत्येक मंगळवारी होणाऱ्या नियोजन बैठकांमध्ये आपला आवाज उठवा.',
    'council.learn': 'अधिक जाणून घ्या',
    'btn.continue': 'सुरू ठेवा',
    'btn.register': 'सदस्य म्हणून नोंदणी करा',
    'btn.processing': 'प्रक्रिया सुरू आहे...',
    'success.registered': 'यशस्वीरित्या नोंदणी झाली!',
    'welcome.council': 'परिषदेत आपले स्वागत आहे, नागरिक',
    'modal.resources': 'सामుदायिक संसाधने',
    'emergency.directory': 'आपत्कालीन निर्देशिका',
    'emergency.helpline': 'नगरपालिका हेल्पलाइन',
    'emergency.police': 'स्थानिक पोलीस स्टेशन',
    'emergency.fire': 'अग्निशमन विभाग',
    'emergency.available': '२४/७ उपलब्ध',
    'council.upcoming': 'आगामी सत्रे',
    'council.register': 'नोंदणी करा',
    'links.quick': 'द्रुत दुवे',
    'notif.title': 'सूचना',
    'settings.logout': 'बाहेर पडा',
  },
  gu: {
    'nav.dashboard': 'ડૅશબોર્ડ',
    'nav.new': 'નવું',
    'nav.complaints': 'ફરિયાદો',
    'hero.welcome': 'સ્વાગત છે,',
    'success.registered': 'સફળતાપૂર્વક નોંધણી થઈ!',
    'settings.logout': 'લૉગ આઉટ',
  },
  kn: {
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.new': 'ಹೊಸದು',
    'nav.complaints': 'ದೂರುಗಳು',
    'hero.welcome': 'ಸ್ವಾಗತ,',
    'success.registered': 'ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!',
    'settings.logout': 'ಲಾಗ್ ಔಟ್',
  },
  ml: {
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.new': 'പുതിയത്',
    'nav.complaints': 'പരാതികൾ',
    'hero.welcome': 'സ്വാഗതം,',
    'success.registered': 'വിജയകരമായി രജിസ്റ്റർ ചെയ്തു!',
    'settings.logout': 'ലോഗ് ഔട്ട്',
  },
  pa: {
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.new': 'ਨਵਾਂ',
    'nav.complaints': 'ਸ਼ਿਕਾਇਤਾਂ',
    'hero.welcome': 'ਸਵਾਗਤ ਹੈ,',
    'success.registered': 'ਸਫਲਤਾਪੂਰਵਕ ਰਜਿਸਟਰ ਹੋਇਆ!',
    'settings.logout': 'ਲੌਗ ਆਉਟ',
  }
};

export function LanguageProvider({ children, initialLanguage }: { children: ReactNode, initialLanguage: string }) {
  const [language, setLanguage] = useState(initialLanguage);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const n = (num: number | string): string => {
    const s = num.toString();
    const map = numberMaps[language];
    if (!map) return s;
    return s.split('').map(char => {
      const digit = parseInt(char, 10);
      return !isNaN(digit) ? map[digit] : char;
    }).join('');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, n }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}
